#!/bin/sh
ssh ubuntu@18.117.86.112<<EOF
    cd ~/github-folder
    sudo -s	
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh 
    nvm install 16.3.0	
    npm install
    npm install -g pm2
    pm2 restart app.js
    exit
EOF